### PR TITLE
fix all issues

### LINKED ISSUE #32: Add client-side validation

### PR DESCRIPTION
**Pull request by MinhQuangDo**
Resolve #32

### CODE REVIEW

File: laravel-7-crud-app/app/Http/Controllers/ContactController.php [hunk 1]
```diff
@@ -64,6 +64,7 @@ public function store(Request $request)
             'zipcode' => $request->get('zipcode'),
             'creator' => Auth::user()->id,
         ]);
+        // dd($request->get('city'));
```
Comment (james-daily) [inline laravel-7-crud-app/app/Http/Controllers/ContactController.php:67]: remove this commented out line.  Don't use `dd()` except as a last resort when other debugging methods aren't working or are unavailable.

File: laravel-7-crud-app/resources/views/contacts/create.blade.php [hunk 2]
```diff
@@ -17,18 +17,18 @@
       <form method="post" action="{{ route('contacts.store') }}">
           @csrf
           <div class="form-group">    
-              <label for="first_name">First Name:</label>
+              <label for="first_name">First Name*:</label>
```
Comment (james-daily) [inline laravel-7-crud-app/resources/views/contacts/create.blade.php:20]: You need to explain what the asterisk means.  Put something like 

* required

on the page.  Or instead of using an asterisk just say "First Name (required)"

File: laravel-7-crud-app/resources/views/contacts/edit.blade.php [hunk 3]
```diff
@@ -20,29 +21,29 @@
             <div class="form-group">
 
                 <label for="first_name">First Name:</label>
```
Comment (james-daily) [inline laravel-7-crud-app/resources/views/contacts/edit.blade.php:23]: Indicate that the field is required with (required) or * required or whatever you decide to use in create.blade.php.  Be consistent.

**Review by james-daily — APPROVED** [review]
